#' An internal customized ggplot2 theme for all the plots
#' generated by ViSAGE
#'
#' @noRd
boris_theme <- function(){
  ggplot2::theme_bw() +
    ggplot2::theme(
      axis.text       = ggplot2::element_text(color = "black", size = 16),
      axis.title      = ggplot2::element_text(colour = "black", face = "bold", size = 16),
      legend.text     = ggplot2::element_text(colour = "black", size = 16),
      legend.position = "none",
      legend.title    = ggplot2::element_blank(),
      panel.grid      = ggplot2::element_blank(),
      panel.background = ggplot2::element_rect(fill = "white", colour = NA),
      panel.border    = ggplot2::element_rect(colour = "black"),
      text            = ggplot2::element_text(colour = "black", size = 16)
    )
}

#####################################################################################################################
## The function below runs the multi-generation future simulation of a population
### It makes selection and crosses for 20 generations and returns 
#' Simulation of 20-generation selection for an initial breeding population 
#'
#' @param pop base population, generation zero
#' @param intensity selection intensity in percentage
#' @param direction selection direction, directional high or low values
#' @param trait target trait for selection; choose one of the three traits 
#' @param crop selected crop among maize, avocado, and strawberry
#' @param SP.crop the simulation paramaters container, an alphaSimR's object
#'
#' @returns a list of three elements: pop.list, a data frame of genetic values, and data frame of phenotypes.
#' @noRd
#'
multi.gener.sim <- function(pop = pop, intensity = 20, direction = "Higher values", 
                            trait, crop = "Maize", SP.crop){
  ####### Embed a simulation --------------- ##
  set.seed(900)
  pop.size = pop@nInd
  col.names <- colnames(pop@gv)
  trait.num = which(col.names == trait)
  direct = ifelse(direction == "Higher values", TRUE, FALSE)
  # h2.list <- list(Maize = c(0.9, 0.7, 0.8), 
  #                 Avocado = c(0.8, 0.8, 0.9), 
  #                 Strawberry = c(0.8, 0.8, 0.7))
  h2.list <- switch(crop,
                    "Maize" = c(0.9, 0.7, 0.8),
                    "Avocado" = c(0.8, 0.8, 0.9),
                    "Strawberry" = c(0.8, 0.8, 0.9),
                    NULL)
  # SP.crop <- switch(crop,
  #                   "Maize" = SP(),
  #                   "Avocado" = SP.avocado(),
  #                   "Strawberry" = SP.strawberry(),
  #                   SP)
  # pop.dt <- data.frame(col.names[1] = NA, col.names[2] = NA, col.names[3] = NA)
  pop.list <- list()
  pop <- AlphaSimR::randCross(pop, nCrosses = 100, nProgeny = 10, simParam = SP.crop)
  pop <- AlphaSimR::setPheno(pop, h2 = h2.list, simParam = SP.crop)
  pop.gv.dt <- data.frame(Generation = rep(0, nrow(pop@gv)), as.data.frame(pop@gv))
  pop.pv.dt <- data.frame(Generation = rep(0, nrow(pop@pheno)), as.data.frame(pop@pheno))
  for(generation in 1:20){
    pop = AlphaSimR::selectCross(pop=pop, use="pheno", nInd = intensity*pop.size/100,
                      nCrosses=100, nProgeny = 10, trait = trait.num, selectTop = direct, 
                      simParam = SP.crop)
    pop = AlphaSimR::setPheno(pop, h2 = h2.list, simParam = SP.crop)
    
    pop.gv.dt.temp <- data.frame(Generation = rep(generation, nrow(pop@gv)),
                              as.data.frame(pop@gv))
    pop.pv.dt.temp <- data.frame(Generation = rep(generation, nrow(pop@pheno)),
                              as.data.frame(pop@pheno))
    pop.gv.dt <- rbind(pop.gv.dt, pop.gv.dt.temp)
    pop.pv.dt <- rbind(pop.pv.dt, pop.pv.dt.temp)
    pop.list[[generation]] <- pop
  }
  combined.dt <- rbind(dplyr::mutate(pop.gv.dt, Type = "Genetic"), 
                       dplyr::mutate(pop.pv.dt, Type = "Phenotypic"))
  out.list <- list(popList = pop.list, gv = pop.gv.dt, pheno = pop.pv.dt, comb = combined.dt)
  return(out.list)
} # End of function multi.gener.sim
#####################################################################################################################


#####################################################################################################################
#' Summarize simulation results
#' 
#' @description
#' Summarize the simulation results by the computing the quantile chosen by the user.#' 
#'
#' @param data The data frame of the simulation results
#' @param quartile Define the quartile from c(25,50,75,100)
#' @param pivot A boolean to determine whether to pivot longer or not
#'
#' @returns A data frame with summarized values
#' @noRd
#'
summary.simulation <- function(data, quartile = 50, pivot = F){
  summary.dt <- dplyr::group_by(data, Generation) |> 
    dplyr::summarise_at(names(data[,-1]), ~ stats::quantile(., probs = quartile/100)) |> 
    dplyr::mutate_at(names(data[,-1]), ~ ifelse(. > 0, ., 2)) |> 
    as.data.frame()
  # pivot_longer(., 2:ncol(data), names_to = "variate", values_to = "values") %>%
  # mutate(., values = ifelse(values > 0, values, 2))
  if(pivot == T){
    summary.dt <- summary.dt |> 
    tidyr::pivot_longer(2:ncol(data), names_to = "variate", values_to = "values") |> 
    as.data.frame()
    # mutate(., values = ifelse(values > 0, values, 2))
  }
  return(summary.dt)
} # End of function summary.simulation
#####################################################################################################################


#####################################################################################################################
### The first argument is the output from the summary.simulation function

#' Draw a genetic gain plot
#'
#' @description
#' A function to draw dot plot to depict the temporal trend of the population 
#' quantile over 20 generations. This function is used in the Fun panel only.
#' 
#' @param dt a data frame of simulated phenotypes across 20 generations. 
#' It is an output from the summary.simulation function.
#' @param trait the desired trait to be plotted.
#' @param col the color of the line and dots plotted
#' @param annotate.bottom A string to be written at the bottom left
#' @param annotate.top A string to be written at the top left
#' @param draw.arrow a boolean to determine whether to draw a horizontal arrow. Default = FALSE.
#'
#' @returns a line graph with dots showing the phenotypes across 20 generations. It is a ggplot2 object.
#' @noRd
#'
draw.genetic.gain.plot <- function(dt, trait, col = "black", annotate.bottom,
                                   annotate.top, draw.arrow = F){
  tmp_dt <- dplyr::filter(dt, variate == trait)
  trait2 <- switch(trait,
                   "StemDiameter" = "Stem diameter (mm)",
                   "TasselLength" = "Tassel length (cm)",
                   "FruitLength" = "Fruit length (cm)",
                   "FruitWidth"  = "Fruit width (cm)",
                   "PlantHeight" = "Plant height (cm)",
                   paste0(trait, " (cm)"))
  
  label.size <- 5
  y.max <- 1.5*max(tmp_dt$values)
  y.min <- 0.5*min(tmp_dt$values)
  p <- ggplot2::ggplot(data = tmp_dt, ggplot2::aes(x = Generation, y = values)) +
    ggplot2::geom_line(linewidth = 1) + ggplot2::geom_point(size = 4, color = col) +
    boris_theme() + ggplot2::labs(y = trait2, x = "Generation") +
    ggplot2::annotate(geom = "text", x = 2, y = 1, label = annotate.bottom, 
                      size =label.size, color = col, fontface = "bold") +
    ggplot2::annotate(geom = "text", x = 2, y = y.max-2, label = annotate.top, 
                      size =label.size, color = col, fontface = "bold")
  
  if(draw.arrow == TRUE){
    p <- p + ggplot2::coord_cartesian(ylim = c(-10, y.max), xlim = c(0,20)) +
      ggplot2::annotate("segment", x = 3, y = -8, xend = 17, yend = -8, linewidth = 2, 
                        color = "black", arrow = ggplot2::arrow()) +
      ggplot2::annotate(geom="text", x= 10, y = -5, label = "Time", size = label.size, 
                        color = "black", fontface = "bold")
  }else{
    p <- p + ggplot2::coord_cartesian(ylim = c(0, y.max), xlim = c(0,20))
  }
  return(p)
} # End of function draw.genetic.gain.plot
#####################################################################################################################
